comment:
  layout: header, changes, diff, sunburst
coverage:
  ignore:
  - RxHttpClientJasonExtensionTests/.*
  status:
    patch: false
    project:
      default:
        target: auto

                  